version: '3.3'

services:
  app:
    image: test-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_database
      SPRING_DATASOURCE_USERNAME: akbar
      SPRING_DATASOURCE_PASSWORD: 01111997
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: akbar
      POSTGRES_PASSWORD: 01111997
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6380:6379"